### ISSUE TITLE
Support for iosX64 and macosX64

### ISSUE THREAD

**Issue by SaeedZhiany** [vooft/kt-uuid#3]
I used [KMP WEB Wizard](https://terrakok.github.io/kmp-web-wizard/) to create my KMP project and I selected all platforms except WASM for the project. now I want to use your library to implement some logic in my project but I'm getting this error when building my project:

```bash
:shared:iosX64Main: Could not resolve io.github.vooft:kt-uuid-core:0.1.0.
Required by:
    project :shared
```

```bash
:shared:macosX64Main: Could not resolve io.github.vooft:kt-uuid-core:0.1.0.
Required by:
    project :shared
```

Is there any chance of getting support for the iosX64 and macosX64 platforms soon? and any other platforms that is not compatible with the Wizard's platforms. Thanks

**Comment by vooft** [comment]
Absolutely, added both in #4, released under `0.2.0`
